### PR TITLE
readme: markdown beautifier

### PR DESCRIPTION
**Pull request by noraj**

### CODE REVIEW

**Comment by s0md3v** [comment]
This project is being no longer maintained and is set for a complete re-write.
Since your PR doesn't fix any existing bugs,  I can't merge it.

**Comment by noraj** [comment]
@s0md3v So can you archive it ? https://help.github.com/articles/archiving-repositories/
It will keep contributor from loosing time to contribute to an unmaintained project.

**Comment by noraj** [comment]
@s0md3v maybe you can also state that on the readme with a big warning.

> This project is being no longer maintained and is set for a complete re-write.

**Comment by noraj** [comment]
@s0md3v You are an ungrateful person and I easily understand why nobody contribute to your project.
You're talking to me about not participating? I spent hundred of hours building, maintaining and making evolve https://inventory.rawsec.ml/ and I know for sure I got only 2 contributions in nearly 1 year, I developed a lib https://gitlab.com/noraj/nvd_api that never got a contribution, I participated in more than 200 OSS project not only making issues or fixing README but also participating to code, I'm maintaining some archlinux packages, etc. 
And you arrogant person, tell me to contribute, where you didn't even made commit in more than 1 year for your own project and abandoned it.
And then you spit to my face fore making pull request to your project, ... what's wrong about fixing your README or adding your tool to a great inventory to make him more popular and maybe getting contributions from it?

You should really read some OSS code of conduct: https://www.contributor-covenant.org/version/1/4/code-of-conduct.html

image

**Comment by noraj** [comment]
I heard your message, you won. I'll never contribute to your projects anymore.

**Comment by noraj** [comment]
Some project are more welcoming:
image

**Comment by s0md3v** [comment]
1. I don't care what you have done or what I have done. We are talking about this particular project and this pull request.

2. Let me remind you, I am managing around 35 repos built from the scratch. It's not easy for me keep developing all the projects simultaneously.

3. I made Striker when I was a complete beginner and yes, it does what it was supposed to do 1 year ago but now I know way much more about both Python and security so instead of improving this, I will completely re-write this from scratch. That's the plan.

4. I have closed at least 3-4 pull requests of yours about that badge thing, can't you see I am not interested in advertising my projects? Can't you stop?

5. I will never merge any pull request related to spelling errors and such.

6. Another reason to close your pull request was because this project is set for a re-write, there is no point in modifying it.

7. Have a nice day mate and stop calling people arrogant just because they don't want to merge a pull request for good reasons.

**Comment by noraj** [comment]
@s0md3v 
`1. I don't care what you have done or what I have done. We are talking about this particular project and this pull request.` then 2\. I am managing around 35 repos`... not talking about this repo only.




>     4\. I have closed at least 3-4 pull requests of yours about that badge thing, can't you see I am not interested in advertising my projects? Can't you stop?

Sorry, I didn't noticed that several projects was owned by you.



>     5\. I will never merge any pull request related to spelling errors and such.

That's stupid... that's not even a reason.

>     6\. Another reason to close your pull request was because this project is set for a re-write, there is no point in modifying it.

That's also stupid because this PR was about the code so even is the code is set for a re-write... And most importantly, **how people are supposed to know** your project is **set for a re-write** because your project is not archived and there is not any mention of that in the README. You want people to read your mind?


>     7\. Have a nice day mate and stop calling people arrogant just because they don't want to merge a pull request for good reasons.

I didn't say you were arrogant because you don't merge the PR but because of the way you speak to me. And your *good reason* is what? this is ok for the badge but there is no reason for the markdown.

I already said this is ok for the badge:

> You should think I asked nothing to you, I don't need visibility or/and I don't like your badge: your are free not to use it.


... well, you're still UN-welcoming and arrogant.

I hate to have to be rude with people, actually you're the first person from hundred of projects reacting like that. Keep dev alone. Adios.

**Comment by s0md3v** [comment]
1. Mentioning that I have 35 repositories is important to explain why I have abandoned this project.
2. I don't consider spelling fixes and such things important. They don't affect the quality of the project. Everyone can have their own opinion on this and hence the author should have the right to make the decision.
3. I haven't archived this project, I am sorry for that, my fault.
4. I am also sorry if you found my words harsh.
5. I get a lot of contributions and I don't know why you think I don't. But yeah, I would definitely like to develop alone instead of people changing **efficeint** to **efficient** in my readme.

**Comment by noraj** [comment]
> I don't consider spelling fixes and such things important. They don't affect the quality of the project. Everyone can have their own opinion on this and hence the author should have the right to make the decision.

It is still stupid not to merge it as someone else did the job for you and that you only have to merge it. Ok you not to take care about spelling or stuff like that, but if someone make a contribution, refusing it is stupid.

> I haven't archived this project, I am sorry for that, my fault.

Yeah that's why I asked in the first time.

> @s0md3v So can you archive it ? https://help.github.com/articles/archiving-repositories/

> I get a lot of contributions and I don't know why you think I don't. But yeah, I would definitely like to develop alone instead of people changing **efficeint** to **efficient** in my readme.

That is what I understood from what you said. Maybe I'm wrong.

> Maybe people should actually contribute to projects instead of adding badges, correcting spelling mistakes, adding .gitignore file or "beautifying" markdown.

And there were not any contrib during 1 year on Blazy so I assumed you didn't received that much contributions.

**Pull request closed without merging**
